export const LANGUAGE_OPTIONS = ["ru", "en"];

export const messages = {
  ru: {
    meta: {
      pageTitle: "BizAnalytics",
      access: "Доступ",
      language: "Язык",
      theme: "Тема",
      apiBase: "API"
    },
    nav: {
      home: "Главная",
      analytics: "Аналитика",
      reports: "Отчеты"
    },
    theme: {
      light: "Светлая",
      dark: "Темная"
    },
    status: {
      initial: "Войдите в систему и начните работать с компаниями, аналитикой и отчетами.",
      sessionExpired: "Сессия истекла. Выполните вход снова.",
      loggedOut: "Вы вышли из системы.",
      createFirstCompany: "Создайте первую компанию, чтобы открыть аналитику и отчеты.",
      companyCreated: "Компания «{name}» создана.",
      companyUpdated: "Компания «{name}» обновлена.",
      companyDeleted: "Компания удалена.",
      analyticsLoaded: "Аналитика обновлена.",
      importSuccess: "Обработка завершена: файлов {files}, записей {count}.",
      reportReady: "PDF-отчет подготовлен и скачивается.",
      marketLoaded: "Рыночные данные обновлены.",
      currencyLoaded: "Данные по курсу валют обновлены.",
      companiesLoaded: "Котировки компаний обновлены.",
      selectCompanyFirst: "Сначала выберите компанию.",
      enterCompanyName: "Введите название компании.",
      chooseFiles: "Выберите хотя бы один файл для анализа."
    },
    errors: {
      auth: "Не удалось выполнить вход.",
      loadCompanies: "Не удалось загрузить компании.",
      saveCompany: "Не удалось сохранить компанию.",
      deleteCompany: "Не удалось удалить компанию.",
      loadAnalytics: "Не удалось загрузить аналитику.",
      importFiles: "Не удалось обработать файлы.",
      loadMarket: "Не удалось загрузить рыночные данные.",
      downloadReport: "Не удалось сформировать PDF-отчет."
    },
    auth: {
      title: "Вход в рабочее пространство",
      subtitle: "Управляйте компаниями, анализируйте документы и таблицы, формируйте отчеты в одном интерфейсе.",
      emailLabel: "Email",
      emailPlaceholder: "analyst@company.com",
      passwordLabel: "Пароль",
      passwordPlaceholder: "Минимум 6 символов",
      loginAction: "Войти",
      registerAction: "Создать аккаунт",
      submitting: "Подождите...",
      switchToRegister: "Нет аккаунта? Зарегистрироваться",
      switchToLogin: "Уже есть аккаунт? Войти",
      backgroundNote: "Гибкая BI-панель для ежедневной работы с показателями, курсами и файлами."
    },
    layout: {
      brand: "BizAnalytics",
      signedInAs: "Вы вошли как",
      logout: "Выйти",
      companyLabel: "Текущая компания",
      chooseCompany: "Выберите компанию",
      noCompanies: "Компаний пока нет"
    },
    home: {
      title: "Компании и рынок",
      subtitle: "Создавайте компании, редактируйте их данные и отслеживайте валюты и рыночные показатели в одном месте.",
      createTitle: "Создание и редактирование компаний",
      createDescription: "Создайте первую компанию и управляйте рабочими пространствами с главной страницы.",
      nameLabel: "Название компании",
      namePlaceholder: "Aurora Trade",
      createAction: "Создать компанию",
      updateAction: "Сохранить изменения",
      cancelEdit: "Отмена",
      listTitle: "Ваши компании",
      listDescription: "На главной можно выбрать активную компанию, изменить ее название или удалить ненужную запись.",
      companyCount: "Компаний: {count}",
      emptyTitle: "Компании еще не созданы",
      emptyBody: "Добавьте первую компанию, чтобы открыть аналитику файлов и экспорт отчетов.",
      selectAction: "Открыть",
      editAction: "Изменить",
      deleteAction: "Удалить",
      deleteConfirm: "Удалить выбранную компанию вместе со связанными данными?",
      selectedBadge: "Активная компания",
      marketTitle: "Курсы валют",
      marketDescription: "Выберите период и валютную пару, чтобы посмотреть динамику курса на интерактивном графике.",
      periodLabel: "Период",
      periodStart: "Начало периода",
      periodEnd: "Конец периода",
      periodWeek: "7 дней",
      periodMonth: "30 дней",
      periodQuarter: "90 дней",
      periodHalfYear: "180 дней",
      baseCurrency: "Базовая валюта",
      quoteCurrency: "Целевая валюта",
      currencyRateLabel: "Курс валюты",
      refreshAction: "Обновить",
      marketPulseTitle: "Котировки ведущих компаний мира",
      marketPulseDescription: "Источник: {source}",
      marketEmpty: "Данные рынка появятся после первой загрузки.",
      rateLabel: "Обновлено",
      changeLabel: "Изменение",
      trendUp: "{base} укрепился к {quote} на {percent}%.",
      trendDown: "{base} ослаб к {quote} на {percent}%.",
      trendFlat: "За выбранный период курс почти не изменился."
    },
    analytics: {
      deleteAnalysesAction: "Удалить анализ",
      deleteHint: "Отметьте анализы вручную или дважды нажмите на любой анализ, чтобы выбрать все.",
      deleteSelectedConfirm: "Вы точно хотите удалить выбранные анализы? Выбрано: {count}.",
      title: "Мультианализ файлов",
      subtitle: "Загружайте до 10 файлов одновременно, объединяйте отчеты по продажам, финансам и успеваемости и получайте единую аналитику.",
      analysesAction: "Анализы",
      currentAnalysisLabel: "Текущий анализ",
      drawerTitle: "Список анализов",
      newAnalysisAction: "Новый анализ",
      compareAnalysesAction: "Сравнить анализы",
      compareHint: "Отметьте анализы в списке, затем нажмите кнопку сравнения.",
      renameFieldLabel: "Название анализа",
      renamePlaceholder: "Например, Аналитика 3",
      saveAnalysisName: "Сохранить",
      cancelAnalysisRename: "Отмена",
      deleteAnalysisConfirm: "Вы точно хотите удалить данную аналитику?",
      deleteYes: "Да",
      deleteNo: "Нет",
      compareSelectedAction: "Сравнить",
      comparingAction: "Сравниваем...",
      comparisonEyebrow: "Сравнение",
      comparisonTitle: "Сравнение выбранных анализов",
      comparisonDescription: "Сводка по каждому анализу показана рядом, чтобы быстро сопоставить ключевые показатели.",
      closeComparisonAction: "Закрыть сравнение",
      comparisonResultTitle: "Итоги сравнения",
      comparisonResultDescription: "Общий вывод по различиям между выбранными анализами.",
      compareRevenueLeader: "По общей выручке лидирует «{name}» с результатом {value}.",
      compareSalesLeader: "По количеству продаж впереди «{name}»: {value}.",
      compareCheckLeader: "Самый высокий средний чек показывает «{name}»: {value}.",
      compareRevenueGap: "Разница по выручке между «{first}» и «{second}» составляет {percent}%.",
      uploadEyebrow: "Импорт",
      uploadTitle: "Загрузка файлов для анализа",
      uploadDescription: "Поддерживаются CSV, XLS, XLSX и DOCX. За один мультианализ можно загрузить до 10 файлов разных типов.",
      fileLabel: "Файлы",
      fileHint: "Форматы: .csv, .xls, .xlsx, .docx. Можно загружать до 10 документов сразу.",
      chooseFilesAction: "Выбрать файлы",
      noFiles: "Файлы еще не выбраны.",
      readyFiles: "Готово файлов: {count}",
      maxFiles: "Можно загрузить не более {count} файлов за один мультианализ.",
      analyzeAction: "Анализ",
      multiAnalyzeAction: "Мультианализ",
      importing: "Анализируется...",
      addMoreFiles: "Добавить файлы",
      removeFile: "Убрать",
      currentCompany: "Текущая компания",
      refreshAction: "Обновить аналитику",
      applyPeriodAction: "Применить период",
      filtersEyebrow: "Фильтры",
      filtersTitle: "Период и рабочая область",
      filtersDescription: "Используйте фильтры дат, чтобы сфокусироваться на нужном интервале уже импортированных данных.",
      startDate: "Дата начала",
      endDate: "Дата окончания",
      summaryTitle: "Сводка",
      revenueTitle: "Динамика выручки",
      revenueDescription: "Показывает, как менялась общая выручка по дням.",
      priceTitle: "Колебания средней цены",
      priceDescription: "Средняя цена единицы товара по дням помогает быстро заметить скачки.",
      sourceTitle: "Сопоставление источников",
      sourceDescription: "Сравнивайте вклад разных файлов в выручку и объем данных после совместной загрузки.",
      productsTitle: "Топ товаров",
      productsDescription: "Лидеры по выручке и количеству за выбранный период.",
      insightsTitle: "Ключевые выводы",
      insightsDescription: "Краткие выводы по последней произведенной аналитике.",
      noDataTitle: "Аналитика пока пустая",
      noDataBody: "Выберите компанию и загрузите хотя бы один файл, чтобы построить сводку, графики и PDF-отчет.",
      totalRevenue: "Общая выручка",
      salesCount: "Количество продаж",
      totalQuantity: "Объем продаж",
      averageCheck: "Средний чек",
      avgPrice: "Средняя цена",
      sourceColumn: "Источник",
      productColumn: "Товар",
      quantityColumn: "Количество",
      revenueColumn: "Выручка",
      recordsColumn: "Записи"
    },
    reports: {
      title: "PDF-отчеты",
      subtitle: "Сформируйте и скачайте PDF по последней аналитике: со сводкой, таблицами и ключевыми выводами.",
      reportEyebrow: "Экспорт",
      reportTitle: "Отчет по выбранному анализу",
      reportDescription: "Отчет собирается на сервере и скачивается в PDF-формате. Перед выгрузкой выберите нужный анализ.",
      analysisSelectLabel: "Выбор анализа",
      generateAction: "Скачать PDF-отчет",
      generating: "Формируем PDF...",
      summaryTitle: "Что войдет в отчет",
      summaryItems: [
        "Сводка по выручке, продажам, количеству и среднему чеку.",
        "Тренд выручки и средняя цена по дням.",
        "Топ товаров и сравнение импортированных источников.",
        "Ключевые выводы по выбранному анализу."
      ],
      noReportTitle: "Нет данных для отчета",
      noReportBody: "Сначала выполните анализ по выбранной компании и нужному анализу, затем вернитесь сюда."
    }
  },
  en: {
    meta: {
      pageTitle: "BizAnalytics",
      access: "Access",
      language: "Language",
      theme: "Theme",
      apiBase: "API"
    },
    nav: {
      home: "Home",
      analytics: "Analytics",
      reports: "Reports"
    },
    theme: {
      light: "Light",
      dark: "Dark"
    },
    status: {
      initial: "Sign in and start working with companies, analytics, and reports.",
      sessionExpired: "Your session expired. Please sign in again.",
      loggedOut: "You have signed out.",
      createFirstCompany: "Create your first company to unlock analytics and reports.",
      companyCreated: "Company \"{name}\" has been created.",
      companyUpdated: "Company \"{name}\" has been updated.",
      companyDeleted: "The company has been deleted.",
      analyticsLoaded: "Analytics has been refreshed.",
      importSuccess: "Import completed: {files} files and {count} records processed.",
      reportReady: "Your PDF report is ready and downloading.",
      marketLoaded: "Market data has been refreshed.",
      currencyLoaded: "Currency data has been refreshed.",
      companiesLoaded: "Company quotes have been refreshed.",
      selectCompanyFirst: "Select a company first.",
      enterCompanyName: "Enter a company name.",
      chooseFiles: "Select at least one file for analysis."
    },
    errors: {
      auth: "Authentication failed.",
      loadCompanies: "Failed to load companies.",
      saveCompany: "Failed to save the company.",
      deleteCompany: "Failed to delete the company.",
      loadAnalytics: "Failed to load analytics.",
      importFiles: "Failed to process the files.",
      loadMarket: "Failed to load market data.",
      downloadReport: "Failed to generate the PDF report."
    },
    auth: {
      title: "Access your workspace",
      subtitle: "Manage companies, analyze documents and spreadsheets, and build reports in one place.",
      emailLabel: "Email",
      emailPlaceholder: "analyst@company.com",
      passwordLabel: "Password",
      passwordPlaceholder: "At least 6 characters",
      loginAction: "Sign in",
      registerAction: "Create account",
      submitting: "Please wait...",
      switchToRegister: "Need an account? Register",
      switchToLogin: "Already have an account? Sign in",
      backgroundNote: "A flexible BI workspace for everyday metrics, files, and market tracking."
    },
    layout: {
      brand: "BizAnalytics",
      signedInAs: "Signed in as",
      logout: "Sign out",
      companyLabel: "Current company",
      chooseCompany: "Choose a company",
      noCompanies: "No companies yet"
    },
    home: {
      title: "Companies and market",
      subtitle: "Create companies, edit their data, and monitor currencies and market signals in one screen.",
      createTitle: "Create and edit companies",
      createDescription: "Create your first company and manage workspaces right from the home page.",
      nameLabel: "Company name",
      namePlaceholder: "Aurora Trade",
      createAction: "Create company",
      updateAction: "Save changes",
      cancelEdit: "Cancel",
      listTitle: "Your companies",
      listDescription: "Use the home page to activate a company, rename it, or remove an outdated workspace.",
      companyCount: "Companies: {count}",
      emptyTitle: "No companies yet",
      emptyBody: "Add your first company to unlock file analytics and PDF exports.",
      selectAction: "Open",
      editAction: "Edit",
      deleteAction: "Delete",
      deleteConfirm: "Delete the selected company and all related data?",
      selectedBadge: "Active company",
      marketTitle: "Currency rates",
      marketDescription: "Choose a period and a currency pair to explore the exchange rate trend on an interactive chart.",
      periodLabel: "Period",
      periodStart: "Period start",
      periodEnd: "Period end",
      periodWeek: "7 days",
      periodMonth: "30 days",
      periodQuarter: "90 days",
      periodHalfYear: "180 days",
      baseCurrency: "Base currency",
      quoteCurrency: "Quote currency",
      currencyRateLabel: "Exchange rate",
      refreshAction: "Refresh",
      marketPulseTitle: "Leading global company quotes",
      marketPulseDescription: "Source: {source}",
      marketEmpty: "Market data will appear after the first refresh.",
      rateLabel: "Updated",
      changeLabel: "Change",
      trendUp: "{base} strengthened against {quote} by {percent}%.",
      trendDown: "{base} weakened against {quote} by {percent}%.",
      trendFlat: "The rate barely changed over the selected period."
    },
    analytics: {
      title: "Multi-file analytics",
      deleteAnalysesAction: "Delete analysis",
      deleteHint: "Select analyses manually or double-click any analysis to select all.",
      deleteSelectedConfirm: "Are you sure you want to delete the selected analyses? Selected: {count}.",
      subtitle: "Upload up to 10 files at once, combine sales, financial, and education reports, and get unified analytics.",
      analysesAction: "Analyses",
      currentAnalysisLabel: "Current analysis",
      drawerTitle: "Analysis list",
      newAnalysisAction: "New analysis",
      compareAnalysesAction: "Compare analyses",
      compareHint: "Mark the analyses you want to compare, then run the comparison.",
      renameFieldLabel: "Analysis name",
      renamePlaceholder: "For example, Analysis 3",
      saveAnalysisName: "Save",
      cancelAnalysisRename: "Cancel",
      deleteAnalysisConfirm: "Are you sure you want to delete this analytics workspace?",
      deleteYes: "Yes",
      deleteNo: "No",
      compareSelectedAction: "Compare",
      comparingAction: "Comparing...",
      comparisonEyebrow: "Comparison",
      comparisonTitle: "Selected analyses comparison",
      comparisonDescription: "Each analysis summary is placed side by side for quick comparison.",
      closeComparisonAction: "Close comparison",
      comparisonResultTitle: "Comparison summary",
      comparisonResultDescription: "A short conclusion based on the selected analyses.",
      compareRevenueLeader: "\"{name}\" leads by total revenue with {value}.",
      compareSalesLeader: "\"{name}\" leads by sales count with {value}.",
      compareCheckLeader: "\"{name}\" has the highest average check: {value}.",
      compareRevenueGap: "The revenue gap between \"{first}\" and \"{second}\" is {percent}%.",
      uploadEyebrow: "Import",
      uploadTitle: "Upload files for analysis",
      uploadDescription: "CSV, XLS, XLSX, and DOCX are supported. One multi-analysis can include up to 10 mixed report files.",
      fileLabel: "Files",
      fileHint: "Formats: .csv, .xls, .xlsx, .docx. You can upload up to 10 documents at once.",
      chooseFilesAction: "Choose files",
      noFiles: "No files selected yet.",
      readyFiles: "Files ready: {count}",
      maxFiles: "You can upload no more than {count} files for one multi-analysis.",
      analyzeAction: "Analyze",
      multiAnalyzeAction: "Multi-analysis",
      importing: "Analyzing...",
      addMoreFiles: "Add files",
      removeFile: "Remove",
      currentCompany: "Current company",
      refreshAction: "Refresh analytics",
      applyPeriodAction: "Apply period",
      filtersEyebrow: "Filters",
      filtersTitle: "Period and workspace",
      filtersDescription: "Use the date filters to focus on a specific time range within the imported dataset.",
      startDate: "Start date",
      endDate: "End date",
      summaryTitle: "Summary",
      revenueTitle: "Revenue trend",
      revenueDescription: "Shows how total revenue changes day by day.",
      priceTitle: "Average price volatility",
      priceDescription: "Daily average unit price helps reveal spikes and drops.",
      sourceTitle: "Source comparison",
      sourceDescription: "Compare how different uploaded files contribute to revenue and total records.",
      productsTitle: "Top products",
      productsDescription: "Best performers by revenue and units sold.",
      insightsTitle: "Key insights",
      insightsDescription: "Quick conclusions from the latest analysis.",
      noDataTitle: "Analytics is empty",
      noDataBody: "Select a company and upload at least one file to populate the dashboard and reports.",
      totalRevenue: "Total revenue",
      salesCount: "Sales count",
      totalQuantity: "Units sold",
      averageCheck: "Average check",
      avgPrice: "Average price",
      sourceColumn: "Source",
      productColumn: "Product",
      quantityColumn: "Quantity",
      revenueColumn: "Revenue",
      recordsColumn: "Records"
    },
    reports: {
      title: "PDF reports",
      subtitle: "Generate and download a PDF for the latest analytics snapshot with summary tables and insights.",
      reportEyebrow: "Export",
      reportTitle: "Report for the selected analysis",
      reportDescription: "The report is composed on the server and downloaded as a PDF. Pick the analysis you want before exporting.",
      analysisSelectLabel: "Analysis",
      generateAction: "Download PDF report",
      generating: "Building PDF...",
      summaryTitle: "Included in the report",
      summaryItems: [
        "Summary metrics for revenue, sales, quantity, and average check.",
        "Revenue trend and average price by day.",
        "Top products and imported source comparison.",
        "Key insights from the selected analysis."
      ],
      noReportTitle: "No data for a report yet",
      noReportBody: "Run analytics for the selected company and analysis first, then return here."
    }
  }
};

export function resolveTemplate(template, params = {}) {
  return Object.entries(params).reduce((result, [key, value]) => {
    return result.replaceAll(`{${key}}`, String(value ?? ""));
  }, template ?? "");
}

export function formatNumberValue(value, language, options = {}) {
  const locale = language === "en" ? "en-US" : "ru-RU";
  return new Intl.NumberFormat(locale, {
    maximumFractionDigits: 2,
    ...options
  }).format(value ?? 0);
}

export function formatDateValue(value, language) {
  if (!value) {
    return "";
  }

  const locale = language === "en" ? "en-GB" : "ru-RU";
  return new Date(value).toLocaleDateString(locale);
}
